version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-card-rec
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-your_root_password} 
      MYSQL_DATABASE: ${MYSQL_DATABASE:-card_recommendation}
      MYSQL_USER: ${MYSQL_USER:-recommendation_team}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-your_password}
    ports:
      - "3306:3306"
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --bind-address=0.0.0.0 
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "recommendation_team", "-p"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mysql_data:
